/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _Carshop;

import org.junit.jupiter.api.Test;

import controller.Customer;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Customer classUnderTest = new Customer();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
