/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package controller;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import dao.Car;
import dao.Customer;

public class CustomerController {
	private static EntityManagerFactory entityManagerFactory;
   public static void main(String[] args) {
	   entityManagerFactory=Persistence.createEntityManagerFactory("Taxil");
	   CustomerController customerController=new CustomerController();
	   customerController.addCustomer();
}
   public void addCustomer() {
	   EntityManager entityManager=entityManagerFactory.createEntityManager();
	   entityManager.getTransaction().begin();
	  Customer customer=new Customer();
	  customer.setName("Taxil");
	  customer.setMobile_No("8238250078");
	  Car car=new Car();
	  car.setCar_name("Mercedes");
	  car.setCar_modelno("S-Class");
	  car.setCustomer(customer);
	  entityManager.persist(car);
	  customer.setCar(car);
	  entityManager.persist(customer);
	  entityManager.getTransaction().commit();
	  entityManager.close();
   }
}
